
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27101/file_db
      username: user
      password: 123
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      location: ${java.io.tmpdir}
server:
  port: 8081